name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Update to your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project (if applicable)
        run: npm run build

      - name: Deploy to VPS
        run: |
          rsync -avz --exclude='node_modules' ./build/ root@185.97.146.100:/home/ubuntu/zeyr-backend
          ssh omer@185.97.146.100 "cd /home/ubuntu/zeyr-backend && npm install && pm2 restart all"
